package model;
// Generated Nov 27, 2018 5:53:45 PM by Hibernate Tools 4.3.1



/**
 * Ikaslea generated by hbm2java
 */
public class Ikaslea  implements java.io.Serializable {


     private int zenbakia;
     private String izena;
     private String abizena1;
     private String abizena2;
     private String microsoftKontua;

    public Ikaslea() {
    }

	
    public Ikaslea(int zenbakia) {
        this.zenbakia = zenbakia;
    }
    public Ikaslea(int zenbakia, String izena, String abizena1, String abizena2, String microsoftKontua) {
       this.zenbakia = zenbakia;
       this.izena = izena;
       this.abizena1 = abizena1;
       this.abizena2 = abizena2;
       this.microsoftKontua = microsoftKontua;
    }
   
    public int getZenbakia() {
        return this.zenbakia;
    }
    
    public void setZenbakia(int zenbakia) {
        this.zenbakia = zenbakia;
    }
    public String getIzena() {
        return this.izena;
    }
    
    public void setIzena(String izena) {
        this.izena = izena;
    }
    public String getAbizena1() {
        return this.abizena1;
    }
    
    public void setAbizena1(String abizena1) {
        this.abizena1 = abizena1;
    }
    public String getAbizena2() {
        return this.abizena2;
    }
    
    public void setAbizena2(String abizena2) {
        this.abizena2 = abizena2;
    }
    public String getMicrosoftKontua() {
        return this.microsoftKontua;
    }
    
    public void setMicrosoftKontua(String microsoftKontua) {
        this.microsoftKontua = microsoftKontua;
    }




}


